### ISSUE TITLE
Could Readme please say how this library differs from IntervalTimer?

### ISSUE THREAD

**Issue by ericfont** [khoih-prog/Teensy_TimerInterrupt#3]
Readme currently mentions how this project is better than TimerOne & TimerThree.  But I'm trying to figure out how exactly does this project differ from IntervalTimer (https://www.pjrc.com/teensy/td_timing_IntervalTimer.html)?  It seems IntervalTimer is limited to a total of 4 IntervalTimer objects on Teensy 3.0-4.1 (and 2 on Teensy LC), so only a total of 4 ISRs.  While your project can do 16 ISRs from 1 hardware timer.  So I guess that means a maximum of 16 * nHardwareTimers.  Is that correct?

So I guess your library can do more ISRs than IntervalTimer?  And what else can it do that IntervalTimer can't?  That would be nice to put in the readme.

Also, I don't know offhard how many hardware timers are available on each board without looking at datasheets, so that would be nice to know too.

**Comment by khoih-prog** [comment]
HI @ericfont 

Thanks for your interest in the library.

I certainly don't and never like to compare and **bad-mouth** other good libraries. It's up to the smart users to compare, post the recommendations, discuss, etc. I also don't have time to test and compare, as thousands of libraries are currently in public domain.

Every library has its strength and weakness, and is normally designed to target certain use-cases.

I certainly appreciate if you can post your experience on the any forum or the [**Discussion** section](https://github.com/khoih-prog/Teensy_TimerInterrupt/discussions) for other users to benefit from your experience.

Using hardware Timer-Interrupt requires some more hardware / firmware experience and knowledge. That's why the related library-writers don't explain and add redundant datasheets in the `README.md`,  but expect the users know how to use, by reading the library code, datasheets, etc.

Thanks for your suggestions anyway, and I'd appreciate it if you can add to the `README.md` or  [**Discussion**](https://github.com/khoih-prog/Teensy_TimerInterrupt/discussions) any good info you'd think beneficial to other users.

I'm closing the issue now as I won't spend time on this
